name: veriscan_mobile
description: "VeriScan - Plateforme anti-contrefaçon au Cameroun"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.3
  mobile_scanner: ^5.2.3
  image_picker: ^1.2.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  provider: ^6.1.2
  geolocator: ^13.0.0
  geocoding: ^3.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#EEF0F8"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#0B0F24"
  image: "assets/images/logo.png"
  android_12:
    color: "#0B0F24"
    image: "assets/images/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/